MovieHub/Models/MovieData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class MovieData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieData()
        {
            this.Seats = new HashSet<Seat>();
        }
    
        public int M_Id { get; set; }
        public string M_Name { get; set; }
        public string M_Category { get; set; }
        public int M_Price { get; set; }
        public System.DateTime M_StartDate { get; set; }
        public System.DateTime M_EndDate { get; set; }
        public string M_Status { get; set; }
        public string M_Description { get; set; }
        public string M_img { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        
        public string M_Banner { get; set; }
        public HttpPostedFileBase BannerFile { get; set; }
        public string M_Duration { get; set; }
        public System.TimeSpan M_ShowtimeStart { get; set; }
        public System.TimeSpan M_ShowtimeEnd { get; set; }
        public int M_ScreenId { get; set; }
    
        public virtual Screen Screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seats { get; set; }
    }
}

MovieHub/Controllers/CinemaController.cs
using MovieHub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieHub.Controllers
{
    public class CinemaController : Controller
    {
        MovieHubDatabaseEntities1 db = new MovieHubDatabaseEntities1();

        // Add Cinema by Admin
        [HttpGet]
        public ActionResult AddCinema()
        {
                return View();
        }
        [HttpPost]
        public ActionResult AddCinema(Cinema c)
        {
                db.Cinemas.Add(c);
                db.SaveChanges();
                return Redirect("Admin");
        }
    
    public ActionResult ShowCinemaData()
        {
                return View(db.Cinemas.ToList());

        }


        // Delete Cinema by Admin
        public ActionResult DeleteCinema(int id)
        {
                Cinema cinema = db.Cinemas.Find(id);
                if (cinema != null)
                {
                    var screens = db.Screens.Where(s => s.S_Cinema_Id == id).ToList();

                    foreach (var screen in screens)
                    {
                        var movieDataList = db.MovieDatas.Where(m => m.M_ScreenId == screen.S_Id).ToList();
                        foreach (var movieData in movieDataList)
                        {
                            var reservedSeats = db.Seats.Where(s => s.Se_Movie_id == movieData.M_Id).ToList();
                            db.Seats.RemoveRange(reservedSeats);
                            db.MovieDatas.Remove(movieData);
                        }
                        db.Screens.Remove(screen);
                    }
                    db.Cinemas.Remove(cinema);
                    db.SaveChanges();
                }
                else
                {
                    ViewBag.ErrorMessage = "Cimena not Exist.";
                }
                return RedirectToAction("AdminPage", "Account");
        }

    }
}

MovieHub/Controllers/MovieDataController.cs
using MovieHub.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieHub.Controllers
{
    public class MovieDataController : Controller
    {
        MovieHubDatabaseEntities1 db = new MovieHubDatabaseEntities1();

        // Add Movie by Admin
        [HttpGet]
        public ActionResult CreateMovie()
        {
                var screens = db.Screens.ToList();
                ViewBag.M_ScreenId = new SelectList(screens, "S_Id", "S_Name");
                return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMovie(MovieData m)
        {
            if (m.M_StartDate.Date <= m.M_EndDate.Date)
            {
                bool movieNotExists = true; // Assume movie does not exist
                ViewBag.ErrorMessage = "Check 3 is incorrect.";

                // Check if db.MovieDatas is empty for the selected screen ID
                if (!db.MovieDatas.Any(x => x.M_ScreenId == m.M_ScreenId))
                {
                    movieNotExists = true; // Skip time validation if no movies exist for the 
                    ViewBag.ErrorMessage = "check 1 is incorrect.";
                }
                else
                {
                    movieNotExists = db.MovieDatas.Any(x => x.M_ScreenId == m.M_ScreenId &&
                        ((m.M_ShowtimeStart < x.M_ShowtimeStart && m.M_ShowtimeEnd < x.M_ShowtimeStart) ||
                        (m.M_ShowtimeStart > x.M_ShowtimeEnd && m.M_ShowtimeEnd > x.M_ShowtimeEnd)));
                    ViewBag.ErrorMessage = "Check2 is incorrect.";

                }

                if (movieNotExists)
                {
                    try
                            {
                                string imageFileName = Path.GetFileNameWithoutExtension(m.ImageFile.FileName);
                                string imageExtension = Path.GetExtension(m.ImageFile.FileName);
                                string imageFilePath = "~/Movies/Images/" + imageFileName + imageExtension;
                                string imagePhysicalPath = Server.MapPath(imageFilePath);
                                m.M_img = imageFilePath;
                                m.ImageFile.SaveAs(imagePhysicalPath);

                                string bannerFileName = Path.GetFileNameWithoutExtension(m.BannerFile.FileName);
                                string bannerExtension = Path.GetExtension(m.BannerFile.FileName);
                                string bannerFilePath = "~/Movies/Banner/" + bannerFileName + bannerExtension;
                                string bannerPhysicalPath = Server.MapPath(bannerFilePath);
                                m.M_Banner = bannerFilePath;
                                m.BannerFile.SaveAs(bannerPhysicalPath);

                                db.MovieDatas.Add(m);
                                db.SaveChanges();
                                return RedirectToAction("AdminPage", "Account");
                            }
                            catch (DbEntityValidationException ex)
                            {
                                // Handle validation errors
                                var errorMessages = ex.EntityValidationErrors
                                    .SelectMany(x => x.ValidationErrors)
                                    .Select(x => x.ErrorMessage);
                                string errorMessage = string.Join("; ", errorMessages);
                                ViewBag.ErrorMessage = "Validation errors: " + errorMessage;
                            }
                            catch (Exception ex)
                            {
                                ViewBag.ErrorMessage = "An error occurred while saving the movie data: " + ex.Message;
                            }
                }
                else
                {
                    ViewBag.ErrorMessage = "Movie already exists in this Screen.";
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Start Date must be earlier than End Date and Start Time must be earlier than End Time.";
            }



            var screens = db.Screens.ToList();
            ViewBag.M_ScreenId = new SelectList(screens, "S_Id", "S_Name");
            return View(m);
        }

        // Show Movie by Admin
        public ActionResult ShowMovieData()
        {
                List<MovieData> movies = db.MovieDatas.ToList();
                return View(movies);
        }

        // Delete Movie by Admin
        public ActionResult Delete(int id)
        {
                MovieData movie = db.MovieDatas.Find(id);
                if (movie != null)
                {
                    var seats = db.Seats.Where(s => s.Se_Movie_id == id);
                    db.Seats.RemoveRange(seats);
                    db.MovieDatas.Remove(movie);
                    db.SaveChanges();
                }
                else
                {
                    ViewBag.ErrorMessage = "Movie does not exist.";
                }
            

            return RedirectToAction("AdminPage", "Account");
        }
    }
}

MovieHub/Controllers/ScreenController.cs
using MovieHub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieHub.Controllers
{
    public class ScreenController : Controller
    {
        MovieHubDatabaseEntities1 db = new MovieHubDatabaseEntities1();

        // Add Screen by Admin
        [HttpGet]
        public ActionResult AddScreen()
        {
                var cinema = db.Cinemas.ToList();
                ViewData["S_Cinema_Id"] = new SelectList(cinema, "C_Id", "C_Name");
                return View();
        }
        [HttpPost]
        public ActionResult AddScreen(Screen s)
        {
                db.Screens.Add(s);
                db.SaveChanges();
                return Redirect("Admin");
        }
        public ActionResult ShowScreenData()
        {
                return View(db.Screens.ToList());
        }
        public ActionResult DeleteScreen(int id)
        {
                Screen screen = db.Screens.Find(id);
                if (screen != null)
                {
                    var movieDataList = db.MovieDatas.Where(m => m.M_ScreenId == id);
                    foreach (var movieData in movieDataList)
                    {
                        var reservedSeats = db.Seats.Where(s => s.Se_Movie_id == movieData.M_Id);
                        db.Seats.RemoveRange(reservedSeats);
                        db.MovieDatas.Remove(movieData);
                    }
                    db.Screens.Remove(screen);
                    db.SaveChanges();
                }
                ViewBag.ErrorMessage = "Screen don't Exist.";
                return RedirectToAction("Admin");
        }
    }
}

MovieHub/Controllers/SeatReservationController.cs
using MovieHub.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace MovieHub.Controllers
{
    public class SeatReservationController : Controller
    {
        MovieHubDatabaseEntities1 db = new MovieHubDatabaseEntities1();

        // Seat Reservation by Customer
        [HttpGet]
        public ActionResult Reservation(int? movieId)
        {
                if (movieId == null)
                {
                    return RedirectToAction("Error");
                }

                List<string> reservedSeatNumbers;

                reservedSeatNumbers = db.Seats
                .Where(s => s.Se_Movie_id == movieId.Value)
                .Select(s => s.Se_Number.ToString()) // Convert to string explicitly
                .ToList();
                // Generate the list of available seat numbers
                List<string> availableSeatNumbers = Enumerable.Range(1, 200)
                    .Where(seatNumber => !reservedSeatNumbers.Contains(seatNumber.ToString()))
                    .Select(seatNumber => seatNumber.ToString())
                    .ToList();

                // Create a SelectList for the dropdown
                ViewBag.AvailableSeatNumbers = new SelectList(availableSeatNumbers);
                return View();
        }

        [HttpPost]
        public ActionResult Reservation(Seat se, int movieId)
        {
            string userName = HttpContext.Request.Cookies["UserName"]?.Value;
            bool seNumberExists = db.Seats.Any(s => s.Se_Number == se.Se_Number && s.Se_Movie_id == movieId);

                if (!seNumberExists)
                {
                    se.Se_Movie_id = movieId;
                    User user = db.Users.FirstOrDefault(u => u.Username == userName);

                    if (user != null)
                    {
                        se.Se_User_id = user.Id;
                        se.Se_UserName = user.FirstName + " " + user.LastName;
                        db.Seats.Add(se);
                        try
                        {
                            db.SaveChanges();
                            TempData["SuccessMessage"] = "Seat created successfully.";

                            return RedirectToAction("LandigPage","Account");
                        }
                        catch (DbEntityValidationException ex)
                        {
                            var errorMessages = ex.EntityValidationErrors
                                .SelectMany(e => e.ValidationErrors)
                                .Select(e => e.ErrorMessage);

                            ModelState.AddModelError("", "Validation errors occurred:");

                            foreach (var errorMessage in errorMessages)
                            {
                                ModelState.AddModelError("", errorMessage);
                            }
                        }
                        return View();
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "User not found.";
                        return View();
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Seat Already Booked.";
                    return View();
                }
        }

        // Show Seat Data for admin
        public ActionResult ShowSeatData()
        {
                List<string> reservedSeatNumbers = db.Seats
                .Select(s => s.Se_Number)
                .ToList();
                var seats = db.Seats.Include(s => s.MovieData).ToList();
                return View(seats);
        }


        // Delete any Seat by Admin
        public ActionResult Delete(int id)
        {
                Seat p = db.Seats.Find(id);
                if (p != null)
                {
                    db.Seats.Remove(p);
                    db.SaveChanges();
                    return View();
                }
                ViewBag.ErrorMessage = "Seat not found.";
                return View();
        }


        [HttpGet]
        public ActionResult SearchSeat()
        {
                return View();
        }

        [HttpPost]
        public ActionResult SearchSeat(string username)
        {
                var matchingSeats = db.Seats.Where(s => s.Se_UserName == username).ToList();

                if (matchingSeats.Count > 0)
                {
                    return View("SearchSeatResults", matchingSeats);
                }
                else
                {
                    ViewBag.ErrorMessage = "No seat reservations found for the given username.";
                    return View("SearchSeat");
                }
        }

        [HttpPost]
        public ActionResult DeleteSeat(int id)
        {
                Seat seat = db.Seats.Find(id);

                if (seat != null)
                {
                    db.Seats.Remove(seat);
                    db.SaveChanges();
                    return View();
                }
                else
                {
                    ViewBag.ErrorMessage = "Seat reservation not found.";
                    return View();
                }
        }


    }
}

MovieHub/Views/MovieData/CreateMovie.cshtml
@model MovieHub.Models.MovieData

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

<style>
    body {
        min-height: 100vh;
        background: linear-gradient(45deg, #90e0ef, #3F5EFB);
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 100% 100%;
        font-family: 'Poppins',sans-serif;
    }

    .form-horizontall {
        background: #ffffff;
        padding: 30px;
        margin-top: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        width: 400px;
        align-content: center
    }

    h4 {
        font-size: 24px;
        margin-bottom: 20px;
        text-align: center;
    }

    label {
        font-weight: bold;
    }

    input[type="text"],
    input[type="date"],
    input[type="time"],
    input[type="file"] {
        width: 100%;
        padding: 8px;
        border-radius: 4px;
        border: 1px solid #ccc;
        box-sizing: border-box;
        font-size: 14px;
    }

    input[type="submit"] {
        background-color: #16bbe8;
        color: black;
        border: none;
        padding: 10px 20px;
        margin-top: 10px;
        font-size: 16px;
        border-radius: 15px;
        cursor: pointer;
        float: right;
    }

        input[type="submit"]:hover {
            background-color: black;
            color: #16bbe8;
        }

    .text-danger {
        color: red;
    }

    #preview {
        max-width: 200px;
        max-height: 200px;
        display: none;
        margin-top: 10px;
    }

    .sidebar {
        margin-top:10px;
        width: 200px;
        background-color: #55f5ff;
        padding: 10px;
        border-radius: 5px;
        float: left;
    }

        .sidebar ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .sidebar li {
            margin-bottom: 10px;
        }

        .sidebar a {
            display: block;
            padding: 8px;
            text-decoration: none;
            color: #333;
        }

            .sidebar a:hover {
                background-color: #ddd;
            }

    .content {
        margin-left: 220px; /* Adjust the margin to leave space for the sidebar */
        margin-bottom: 1300px;
    }

</style>


<div class="sidebar">
    <ul>
        <li class="nav-item">@Html.ActionLink("Show Cinema", "ShowCinemaData", "Cinema")</li>
        <li class="nav-item">@Html.ActionLink("Add Movie", "CreateMovie", "MovieData")</li>
        <li class="nav-item">@Html.ActionLink("Show Moive", "ShowMovieData", "MovieData")</li>
        <li class="nav-item">@Html.ActionLink("Add Screen", "AddScreen", "Screen")</li>
        <li class="nav-item">@Html.ActionLink("Show Screens", "ShowScreenData", "Screen")</li>
        <li class="nav-item">@Html.ActionLink("Search Seat", "SearchSeat", "SeatReservation")</li>
</div>


<div class="content">

    @using (Html.BeginForm("CreateMovie", "MovieData", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="d-flex align-items-center justify-content-center">
            <div class="form-horizontall ">
                <h4>MovieData</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
               
                <div>
                    @ViewBag.ErrorMessage;
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <label for="moviename">Movie Name:</label>
                        @Html.TextBoxFor(model => model.M_Name, new { @placeholder = "Enter the movie name" })
                        @Html.ValidationMessageFor(model => model.M_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="category">Category:</label>
                        @Html.TextBoxFor(model => model.M_Category, new { @placeholder = "Enter the movie category" })
                        @Html.ValidationMessageFor(model => model.M_Category, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="category">Price:</label>
                        @Html.EditorFor(model => model.M_Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.M_Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="startdate">Start Date:</label>
                        <input type="date" class="" name="M_StartDate" id="M_StartDate" />
                        @Html.ValidationMessageFor(model => model.M_StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="enddate">End Date:</label>
                        <input type="date" class="" name="M_EndDate" id="M_EndDate" />
                        @Html.ValidationMessageFor(model => model.M_EndDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="MovieStatus">Movie Status:</label>
                        @Html.TextBoxFor(model => model.M_Status, new { @placeholder = "Enter the movie status" })
                        @Html.ValidationMessageFor(model => model.M_Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="Description">Description:</label>
                        @Html.TextBoxFor(model => model.M_Description, new { @placeholder = "Enter the movie description" })
                        @Html.ValidationMessageFor(model => model.M_Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="MovieImage">Movie Image:</label>
                        <input type="file" name="ImageFile" id="ImageFile" class="" onchange="previewImage()" required />
                        <img id="preview" src="#" alt="Preview" />
                        @Html.ValidationMessageFor(model => model.M_img, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">

                    <div class="col-md-10">
                        <label for="category">Movie Banner:</label>
                        <input type="file" class="form-control" id="BannerFile" name="BannerFile" />
                        @Html.ValidationMessageFor(model => model.M_Banner, "", new { @class = "text-danger" })
                    </div>
                </div>


                <script>
                    function previewImage() {
                        var fileInput = document.getElementById('ImageFile');
                        var preview = document.getElementById('preview');

                        if (fileInput.files && fileInput.files[0]) {
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                preview.src = e.target.result;
                                preview.style.display = 'block';
                            }
                            reader.readAsDataURL(fileInput.files[0]);
                        }
                    }
                </script>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="category">Movie Duration:</label>
                        @Html.EditorFor(model => model.M_Duration, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.M_Duration, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="StartTime">Movie Start Time:</label>
                        <input type="time" class="" name="M_StartTime" id="M_StartTime" />
                        @Html.ValidationMessageFor(model => model.M_ShowtimeStart, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="EndTime">Movie End Time:</label>
                        <input type="time" class="" name="M_EndTime" id="M_EndTime" />
                        @Html.ValidationMessageFor(model => model.M_ShowtimeEnd, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="category">Screen ID:</label>

                        @{
                            var movieList = ViewData["M_ScreenId"] as IEnumerable<SelectListItem>;
                            if (movieList != null)
                            {
                                @Html.DropDownList("M_ScreenId", movieList, htmlAttributes: new { @class = "form-control" })
                            }
                            else
                            {
                                <p>No movies found.</p>
                            }
                        }
                        @*@Html.DropDownList("M_ScreenId", null, htmlAttributes: new { @class = "form-control" })*@
                        @Html.ValidationMessageFor(model => model.M_ScreenId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Create" class="" />
                    </div>
                </div>
            </div>
        </div>
    }
</div>
@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@